### ISSUE TITLE
Boards Manager URL

### ISSUE THREAD

**Issue by drewgates** [01Space/ESP32-C3FH4-RGB#1]
Is there a boards manager URL for support in Arduino and/or PlatformIO?

**Comment by didn0t** [comment]
I'm just using:

https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json,https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_dev_index.json 

and setting board to ESP32C3 Dev Module.

**Comment by drewgates** [comment]
Thanks for the tip! I was able to get it working.

For anyone else who finds their way here:

I'm using Arduino IDE 1.8.19 and ESP32 SDK 2.0.2. A Banggood user helpfully reminded me that putting the board into programming mode requires holding down the B button while you and press and release the R button (reset). 

Press B, press R, release R, release B. 

If you do that while your code is compiling, you should be good to go.
