### ISSUE TITLE
Serial Monitor does not work

### ISSUE THREAD

**Issue by Kian-Wee** [01Space/ESP32-C3FH4-RGB#2]
Uploading of sketches and other functionality seems to be working fine but the Serial monitor does not seem to display any print statements even after installing zadig drivers

**Comment by didn0t** [comment]
I initially had this issue but managed to get it working on a Mac by pressing reset then B button after boot.

**Comment by Kian-Wee** [comment]
> I initially had this issue but managed to get it working on a Mac by pressing reset then B button after boot.

Unfortunately, this doesn't seem to work for me on either of the board I purchased. May I clarify with you if you used the same COM port for uploading the sketch and viewing the serial monitor?

**Comment by didn0t** [comment]
Yes it was, I'll try and double check the settings when I get a chance

**Comment by didn0t** [comment]
Serial works for me with "CDC enable on boot" set to true

**Comment by Kian-Wee** [comment]
Thanks for the help. I managed to get it somewhat working by following all the steps you mentioned. In addition, I realized that the serial monitor has to be closed and reopened for it to function(on windows).
