### ISSUE TITLE
Default firmware

### ISSUE THREAD

**Issue by manj9501** [01Space/ESP32-C3FH4-RGB#3]
Hi 01Space!
Really cool project, I just bought one from Banggood.

I was wondering if you can also provide the factory firmware as a .ino or a .bin file in this repository?
It would be really helpful.

Thanks in advance!
M

**Comment by drewgates** [comment]
From [Adafruit's Learn page here](https://learn.adafruit.com/adafruit-metro-esp32-s2?view=all).

"The ESP32-S2 has a built in bootloader, which means you never have to worry about 'bricking' your board. You can use it to load code directly, say CircuitPython or the binary output of an Arduino compilation or you can use it to load a second bootloader on, like UF2 which has a drag-n-drop interface."

The ROM bootloader can never be disabled or erased, so its always there if you need it!

**Comment by manj9501** [comment]
Hi @drewgates 
I was actually referring to the default 'sketch' that runs on the board out of the box.

**Comment by drewgates** [comment]
I believe my boards arrived flashed with the Blink without delay sketch [in this repo](https://github.com/01Space/ESP32-C3FH4-RGB/tree/main/BlinkWithoutDelay).

**Comment by manj9501** [comment]
Oh okay but mine was a different one so.

**Comment by andypiper** [comment]
Mine had a [sequence of rainbows and checkerboard patterns](https://www.youtube.com/watch?v=SQO4Dn0vE3k) installed - I don’t think it is one of these sketches. I’d be curious to see it, as well. Also this is an ESP32-C3 not the S2, I haven’t tried CircuitPython yet, but MicroPython or the Espressif Dev Arduino core for the C3 will work.

**Comment by drewgates** [comment]
@manj9501 any chance you have a video of what you're looking for?

**Comment by manj9501** [comment]
@drewgates It's basically the one @andypiper had on their board.
Here you go: https://youtu.be/6arZbpNtjD8

It's not the full pattern but I managed to record a significant portion of it.

**Comment by andypiper** [comment]
It is:

- fill all pixels 1-by-1 in Red
- fill all pixels 1-by-1 in Green
- fill all pixels 1-by-1 in Blue
- then repeat:
  - flash checkerboard patterns in white, red, blue multiple times
  - fill all pixels in rainbow sequence several times

**Comment by manj9501** [comment]
Thanks for summing it up though @andypiper

**Comment by manj9501** [comment]
Well, I've been such a nincompoop! 
The default sketch happens to be sketch which I've been ignoring all this while in this repo, the [strandtest_wheel](https://github.com/01Space/ESP32-C3FH4-RGB/tree/main/strandtest_wheel) example.

I guess I should have done my due diligence before opening this issue.

**Comment by andypiper** [comment]
Ha, I was mistaken as well - well figured out.
