### ISSUE TITLE
Arduino WiFi Working?

### ISSUE THREAD

**Issue by didn0t** [01Space/ESP32-C3FH4-RGB#6]
Does anyone have a working example using Wifi?  I've tried a few libraries that I know work with other ESP32 boards but no luck on this board.  

I also noticed some green flashing leds on the matrix when trying to join my AP.

If not I'll try MicroPython next.  Tinygo and neopixel works but no WiFi libs.

**Comment by andypiper** [comment]
Interesting! It should work fine on WiFi - see the `standalone` example in the [Wordle Device repo](https://github.com/ccattuto/wordle-device). I’ll see if I can build a more minimal example at some point. 

MicroPython examples and flash instructions at https://github.com/andypiper/fivebyfive and the `cheerlights` code uses WiFi. I’ve yet to try TinyGo - any example? I’m curious to learn as much about this board as I can :-)

**Comment by ccattuto** [comment]
Not Arduino-related, but for me increasing the max TX power was critical (`PHY` section in the components configuration menu). My `sdkconfig.defaults` contains the following:
```
CONFIG_IDF_TARGET="esp32c3"
CONFIG_ESPTOOLPY_FLASHSIZE_4MB=y
CONFIG_ESP_PHY_MAX_WIFI_TX_POWER=12
```

**Comment by didn0t** [comment]
I've tried with MicroPython and I can scan and see my local APs but attempts to connect don't work.  I've tried with two different boards and am sitting very close to AP.

**Comment by ccattuto** [comment]
I had a similar behavior with the `wifi/getting_started/station` example of the ESP-IDF development framework. I could see APs but I couldn't connect, even at close range, until I changed the max TX power.

**Comment by didn0t** [comment]
Thanks, I've not tired the ESP-IDF framework yet, I'll take a look at that next.  Not sure if the Arduino WiFi libs allow you to adjust this.

**Comment by didn0t** [comment]
Seems to work in Arduino using:

WiFi.setTxPower(WIFI_POWER_5dBm);

Thanks!

**Comment by andypiper** [comment]
interesting - was that with one of the ESP32C3 examples from Espressif, or hand-rolled code?

**Comment by ccattuto** [comment]
Both. The plain `wifi/getting_started/station` doesn't work for me without that modification, but it's possible it's AP-dependent.

**Comment by didn0t** [comment]
Just based on the Wifi example in Arduino IDE:

```
#include <WiFi.h>

char ssid[] = "ssid";
char pass[] = "password";

void setup()
{
  Serial.begin(115200);
  WiFi.mode(WIFI_STA);
  delay(100);
  WiFi.setTxPower(WIFI_POWER_5dBm);
  WiFi.begin(ssid, pass);
  delay(5000);
}
```

**Comment by andypiper** [comment]
Out of curiosity, if you log anything to the console with Serial.print(), do you see any output? I'm getting the board to connect to wifi, but I'm not seeing anything in the serial monitor on the Arduino IDE, which is weird.

**Comment by didn0t** [comment]
Yes I am seeing the same issue, as soon as the Wifi is initialised the serial connection drops.

**Comment by manj9501** [comment]
@andypiper @didn0t I observed similar behavior on my device.

**Comment by andypiper** [comment]
This is a known issue in the ESP Arduino Core, and is fixed in the main GitHub repo. I have a note about it in [my main multi-language repo here](https://github.com/andypiper/fivebyfive/blob/main/notes.md#arduino). Wifi works, but in order to have it work with the serial console you will need a bleeding-edge version of the ESP tooling right now.

**Comment by didn0t** [comment]
@andypiper Thanks for the update, that is good to know.  

I've just pushed my first project to https://github.com/didn0t/5x5_Clock  Would have been a lot easier with working serial!

**Comment by andypiper** [comment]
Going to give that a try, and will add to my notes (wiki-to-be) as another project in the community. Cool! Thanks for sharing, Paul!
