### ISSUE TITLE
Anybody tried to flash WLED?

### ISSUE THREAD

**Issue by ozett** [01Space/ESP32-C3FH4-RGB#8]
anybody treid to put WLED on this C3 ?

https://github.com/Aircoookie/WLED

**Comment by andypiper** [comment]
Not yet, but I have thought about it! I guess that there is less value in using the individual LEDs than in using the whole array as a single colour, but it could be fun to play with it as a "strip". Adding this to my "to try" list.

**Comment by ozett** [comment]
i key an eye on this here, for the case its going to be top of the list.
fiddling WLED to the C3 could be a thing...

**Comment by andypiper** [comment]
I can confirm that it is not possible to flash the existing WLED binary builds directly, so it likely needs to be built specifically for a C3. I'll take a look when I have time (added to [the todo list](https://github.com/andypiper/fivebyfive/blob/main/notes.md#non-micropython) in my fivebyfive project)

**Comment by andypiper** [comment]
(correction - it is totally possible to flash the firmware, but nothing happens with the board when it is installed - no WiFi hotspot to connect and configure)

**Comment by andypiper** [comment]
See these issues on WLED
https://github.com/Aircoookie/WLED/issues/1940
https://github.com/Aircoookie/WLED/issues/2518

Basically WLED currently doesn't allow GPIO8 to be used without the code being modified, and there are some wifi issues. I've built WLED locally and have the board on my network, but I cannot currently get the LEDs to work.

**Comment by ozett** [comment]
[wifi reboots](https://github.com/Aircoookie/WLED/issues/1940) seems related to the expressif core
and the [GPIO8](https://github.com/Aircoookie/WLED/issues/1940) seems to be fixable within wled-code,

but booth things needs some development, i guess.
the c3 is becoming popular, maybe it takes only [some weeks for the experienced developers](https://github.com/Aircoookie/WLED/issues/1940#issuecomment-1096438635)?

**Comment by andypiper** [comment]
Yes, it is definitely possible. I doubt that 01Space would create a WLED distribution directly, this repository is just some example code and schematics. 

Btw I added [GitHub Discussions to my fivebyfive repository](https://github.com/andypiper/fivebyfive/discussions) for this reason - this conversation is probably more of a general idea rather than an issue with the code in this repo 😄

**Comment by 01Space** [comment]
Temporarily not supported， I am creating an esp32 Pico D4 WLED board

**Comment by ozett** [comment]
looks like your already selling the pico d4 on aliexpress, Great.
confirmation that WLED runs on your board?

![image](https://user-images.githubusercontent.com/5937811/168844382-f3abfc81-f773-48ad-9f36-727c2a3908b5.png)

**Comment by andypiper** [comment]
I have the D4 board but have not tried to flash WLED on there as yet. Will report back when I do.

**Comment by 01Space** [comment]
I'll try it tonight and report the results to you later

**Comment by 01Space** [comment]
Pico D4 RGB development board can run WLED firmware

**Comment by ozett** [comment]
Great News...

Transport-cost to EUrope are half of the board price... 😢

**Comment by 01Space** [comment]
You need to modify the code and recompile it before you can use it. You only need to modify two lines of code and change the port of LED and the target name of board
